apps/organization/urls.py
from django.urls import path, include
from .views import OrgView, AddUserAskVies, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView
from .views import TeacherListView, TeacherDetailView

app_name = '[organization]'

urlpatterns = [
    # 课程首页
    path('list/', OrgView.as_view(), name="org_list"),
    path('add_ask/', AddUserAskVies.as_view(), name="add_ask"),
    path('home/<org_id>/', OrgHomeView.as_view(), name="org_home"),
    path('course/<org_id>/', OrgCourseView.as_view(), name="org_course"),
    path('desc/<org_id>/', OrgDescView.as_view(), name="org_desc"),
    path('teacher/<org_id>/', OrgTeacherView.as_view(), name="org_teacher"),

    # 机构收藏
    path('add_fav/', AddFavView.as_view(), name="add_fav"),

    # 教师列表页
    path('teachers/list/', TeacherListView.as_view(), name="teacher_list"),

    # 教师详情页
    path('teachers/<teacher_id>/', TeacherDetailView.as_view(), name="teacher_detail"),

]

apps/users/urls.py
from django.urls import path, include
from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyCourseView, MyFacOrgView
from .views import MyFavTeacherView, MyFavCourseView, MyMessageView
app_name = '[users]'

urlpatterns = [
    # 用户信息
    path('info/', UserinfoView.as_view(), name="user_info"),

    # 用户头像上传
    path('image/upload/', UploadImageView.as_view(), name="image_upload"),

    # 用户个人中心修改密码
    path('update/pwd/', UpdatePwdView.as_view(), name="update_pwd"),

    # 发送邮箱验证码
    path('sendemail_code/', SendEmailCodeView.as_view(), name="sendemail_code"),

    # 修改邮箱
    path('update_email/', UpdateEmailView.as_view(), name="update_email"),

    # 我的课程
    path('mycourse/', MyCourseView.as_view(), name="mycourse"),

    # 收藏的课程机构
    path('myfav/org/', MyFacOrgView.as_view(), name="myfav_org"),

    # 收藏的讲师
    path('myfav/teacher/', MyFavTeacherView.as_view(), name="myfav_teacher"),

    # 收藏的课程
    path('myfav/course/', MyFavCourseView.as_view(), name="myfav_course"),

    # 我的消息
    path('mymessage/', MyMessageView.as_view(), name="mymessage"),

]

courseonline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve
from django.conf.urls.static import static

from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView, IndexView
from courseonline.settings import MEDIA_ROOT, MEDIA_URL, STATIC_URL
from users.views import page_error, page_not_found
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', IndexView.as_view(), name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('captcha/', include('captcha.urls')),
    path('active/<active_code>/', ActiveUserView.as_view(), name="user_active"),
    path('forget/', ForgetPwdView.as_view(), name="forget_pwd"),
    path('reset/<active_code>/', ResetView.as_view(), name="reset_pwd"),
    path('modify_pwd/', ModifyPwdView.as_view(), name="modify_pwd"),
    path('logout/', LogoutView.as_view(), name="logout"),

    # 课程机构url配置
    path('org/', include('organization.urls', namespace="org")),

    # 课程相关url配置
    path('course/', include('courses.urls', namespace="course")),

    # 个人信息相关url配置
    path('users/', include('users.urls', namespace="users")),

]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)  # 配置图片上传函数

# urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

# 全局404页面配置
handler404 = page_not_found

# 全局500页面配置
handler500 = page_error

apps/courses/models.py
from django.db import models
from datetime import datetime
from organization.models import CourseOrg, Teacher
# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u"课程机构", null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name=u"课程名")
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    detail = models.TextField(verbose_name=u"课程详情")
    degree = models.CharField(choices=(("cj", u"初级"), ("zj", u"中级"), ("gj", u"高级")), max_length=2, verbose_name=u"难度")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    is_banner = models.BooleanField(default=False, verbose_name=u"是否轮播")
    teacher = models.ForeignKey(Teacher, verbose_name=u"讲师", on_delete=models.CASCADE, null=True, blank=True)
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    category = models.CharField(max_length=20, verbose_name=u"课程类别", default=u"后端开发")
    tag = models.CharField(default="", verbose_name=u"课程标签", max_length=10)
    need_know = models.CharField(max_length=300, verbose_name=u"课程需知", default="")
    teacher_tell = models.CharField(max_length=300, verbose_name=u"知识点", default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    def get_chapter_num(self):
        # 获取课程章节数
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:3]

    def get_course_lesson(self):
        # 获取课程所有章节
        return self.lesson_set.all()

    def __str__(self):
        return "{0}".format(self.name)


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        """获取章节视频"""
        return self.video_set.all()

    def __str__(self):
        return "{0}<{1}>".format(self.course, self.name)


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    url = models.CharField(max_length=200, default="", verbose_name=u"访问地址")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")
    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}在线{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href=" {% static 'css/reset.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/animate.css' %} ">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/style.css' %} ">
    {% block cusstom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block cusstom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->
                    {% if request.user.is_authenticated %}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.email }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="/static/media/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="/static/media/image/2016/12/default_big_14.png"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>bobby</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url '[users]:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                            <a href="{% url 'users:mymessage' %}">
                                <div class="msg-num"> <span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                            </a>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>

                    {% endif %}

				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% if request.path == '/' %}class="active" {% endif %}><a href="{% url 'index' %}">首页</a></li>
							<li {% if request.path|slice:'7' == '/course' %} class="active" {% endif %}>
								<a href="{% url '[courses]:course_list' %}">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li {% if request.path|slice:'13' == '/org/teachers' %} class="active"{% endif %}>
								<a href="{% url '[organization]:teacher_list' %}">授课教师</a>
							</li>
							<li {% if request.path|slice:'9' == '/org/list' %} class="active"{% endif %}><a href="{% url '[organization]:org_list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
{#                <li>课程机构</li>#}
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}

{% endblock %}

{% block custom_js %}

{% endblock %}
<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.jpg' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl"></span>
                <span class="fr"></span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
<script>
    $(function(){
        $('#jsStayBtn').on('click', function(){
            $.ajax({
                cache: false,
                type: "POST",
                url:"/org/add_ask/",
                data:$('#jsStayForm').serialize(),
                async: true,
                success: function(data) {
                    if(data.status == 'success'){
                        $('#jsStayForm')[0].reset();
                        alert("提交成功")
                    }else if(data.status == 'fail'){
                        $('#jsCompanyTips').html(data.msg)
                    }
                },
            });
        });
    })

</script>


</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %}
    在线
{% endblock %}

{% block custom_bread %}

{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

{% block content %}
<!--banner start-->
<div class="banner">
<div class="wp">
    <div class="fl">
        <div class="imgslide">
            <ul class="imgs">
                {% for banner in all_banners %}

                <li>
                        <a href="{{ banner.url }}">
                            <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                        </a>
                    </li>

                {% endfor %}


            </ul>
        </div>
        <div class="unslider-arrow prev"></div>
        <div class="unslider-arrow next"></div>
    </div>

    </div>


</div>
<!--banner end-->
<!--feature start-->
<section>
<div class="wp">
<ul class="feature">
    <li class="feature1">
        <img class="pic" src="{% static 'images/feature1.png' %}"/>
        <p class="center">专业权威</p>
    </li>
    <li class="feature2">
        <img class="pic" src="{% static 'images/feature2.png' %}"/>
        <p class="center">课程最新</p>
    </li>
    <li class="feature3">
        <img class="pic" src="{% static 'images/feature3.png' %}"/>
        <p class="center">名师授课</p>
    </li>
    <li class="feature4">
        <img class="pic" src="{% static 'images/feature4.png' %}"/>
        <p class="center">数据真实</p>
    </li>
</ul>
</div>
</section>
<!--feature end-->
<!--module1 start-->
<section>
<div class="module">
<div class="wp">
    <h1>公开课程</h1>
    <div class="module1 eachmod">
        <div class="module1_1 left">
            <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
            <p class="fisrt_word">名师授课<br/>专业权威</p>
            <a class="more" href="{% url '[courses]:course_list' %}">查看更多课程 ></a>
        </div>
        <div class="right group_list">
            <div class="module1_2 box">
                <div class="imgslide2">
                    <ul class="imgs">
                    {% for banner_course in banner_courses %}
                        <li>
                            <a href="{% url '[courses]:course_detail' banner_course.id %}">
                                <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                            </a>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow2 prev"></div>
                <div class="unslider-arrow2 next"></div>
            </div>
                {% for course in courses %}
                <div class="module1_{{ forloop.counter|add:2 }} box">
                    <a href="{% url '[courses]:course_detail' course.id %}">
                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="{% url '[courses]:course_detail' course.id %}">
                            <h2 title="{{ course.name }}">{{ course.name }}</h2>
                        </a>
                        <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                        <span class="fr">学习人数：{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl" title="{{ course.course_org }}">{{ course.course_org }}</span>
                        <span class="star fr">0</span>
                    </div>
                </div>
                {% endfor %}
        </div>
    </div>
</div>
</div>
</section>
<section>
<div class="module greybg">
<div class="wp">
    <h1>课程机构</h1>
    <div class="module3 eachmod">
        <div class="module3_1 left">
            <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
            <p class="fisrt_word">名校来袭<br/>权威认证</p>
            <a class="more" href="{% url '[organization]:org_list' %}">查看更多机构 ></a>
        </div>
        <div class="right">
            <ul>
                {% for org in course_orgs %}
                    <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                        <a href="{% url '[organization]:org_home' org.id %}">
                            <div class="company">
                                <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                <div class="score">
                                    <div class="circle">
                                        <h2>{{ org.tag }}</h2>
                                    </div>
                                </div>
                            </div>
                            <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                        </a>
                    </li>

                {% endfor %}
            </ul>
        </div>
    </div>
</div>
</div>
</section>
<!--module1 end-->
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页 - 慕学网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

                <div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
					<!--登录后跳转-->
                     {% if request.user.is_authenticated %}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.email }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="/static/media/image/2016/12/default_big_14.png"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="/static/media/image/2016/12/default_big_14.png"/></dt>
	                                <dd>
	                                    <h2>django</h2>
	                                    <p>bobby</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url '[users]:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'users:mymessage' %}">
                            <div class="msg-num"> <span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                        </a>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>

                    {% endif %}

				</div>
			</div>


    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    慕课网
                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}已收藏{% else %}收藏{% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url "org:org_list" %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url '[organization]:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url '[organization]:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url '[organization]:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url '[organization]:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
    {% block right_form %}
    {% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url "org:add_fav" %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的收藏{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url '[users]:myfav_org' %}">课程机构</a> </li>
                        <li><a href="{% url '[users]:myfav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url '[users]:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">

                        {% for fav_course in course_list %}

                        <div class="module1_5 box">
                            <a href="{% url '[courses]:course_detail' fav_course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url '[courses]:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
                            </div>
                        </div>

                        {% endfor %}


                    </div>
                </div>
            </div>
    </div>
{% endblock %}


